name: Check Syntax

on:
  push:
    branches:
      - "**"

jobs:
  check-syntax:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y python3 php

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.py
            **/*.sh
            **/*.php

      - name: Check syntax
        run: |
          for f in ${{ steps.changed-files.outputs.all_changed_files }}; do 
            extension=$(basename "$f" | cut -d "." -f2)
            echo "Processing file: $f"

            if [ "$extension" == 'py' ]; then
              python3 -m py_compile "$f"
            fi
            if [ "$extension" == 'sh' ]; then
              bash -n "$f"
            fi
            if [ "$extension" == 'php' ]; then
              php -l "$f"
            fi

            if [ $? -ne 0 ]; then 
              echo "Syntax error in $f"
              exit 1 
            fi
          done
